# I2C 键盘配置文件
# 格式: [物理按键编号]=[Linux按键名]
#       EXIT_KEY=[物理按键编号]
#       BLACKLIST=[进程名]

# --- 按键映射 (根据你的新布局) ---
#  空    W     空    1
#  A  Space  D    2
#  Tab  S   Enter 3
# Ctrl Esc   C   Exit

# 1= 
2=w
# 3= 
4=tab

5=a
6=space
7=d
8=esc

9=ctrl
10=s
11=c
12=enter

13=1
14=2
15=3
# 16= (被 EXIT_KEY 指定)

# --- 特殊功能键 ---
EXIT_KEY=16 # 指定物理按键 16 为退出键

# --- 退出黑名单 (可以有多行) ---
BLACKLIST=nesemu_rv1103
BLACKLIST=pocketpy
