target-version = "py312"

exclude = ["backup/**/*.py", "scripts/**/*.py", "pocketpy/**/*.py"]

builtins = ["current_game", "current_world", "current_io", "String", "ellipsis"]

[lint]
ignore = [
    "F405", "F403",     # allow wildcard imports
    "E401",             # allow multiple imports on one line
    "E402",             # allow import outside top-level
    "F401",             # allow unused imports
    "E731",             # allow assignment from lambda
]
